# Generated by Django 4.0.4 on 2022-05-29 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felhasznalo',
            name='egyenleg',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='gyujtes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cim', models.CharField(max_length=255)),
                ('leiras', models.TextField()),
                ('promocios', models.BooleanField(default=False)),
                ('minAr', models.IntegerField()),
                ('cel', models.IntegerField()),
                ('publikalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
