# Generated by Django 4.0.4 on 2022-06-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_felhasznalo_egyenleg_gyujtes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyujtes',
            name='jelenleg',
            field=models.IntegerField(default=0),
        ),
    ]
