# Generated by Django 4.0.4 on 2022-06-06 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_gyujtes_jelenleg'),
    ]

    operations = [
        migrations.CreateModel(
            name='fizetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mennyit', models.IntegerField()),
                ('megjegyzes', models.CharField(max_length=255, null=True)),
                ('gyujtesnek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gyujtes')),
                ('ki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
