# Generated by Django 4.0.4 on 2022-06-18 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fizetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fizetes',
            name='datum',
            field=models.DateField(default=datetime.date(2022, 6, 18)),
        ),
        migrations.AddField(
            model_name='fizetes',
            name='ido',
            field=models.TimeField(default=datetime.time(17, 38, 53, 341146)),
        ),
        migrations.AddField(
            model_name='gyujtes',
            name='datum',
            field=models.DateField(default=datetime.date(2022, 6, 18)),
        ),
        migrations.AddField(
            model_name='gyujtes',
            name='ido',
            field=models.TimeField(default=datetime.time(17, 38, 53, 340340)),
        ),
    ]
