# Generated by Django 4.0.4 on 2022-06-19 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fizetes_datum_fizetes_ido_gyujtes_datum_gyujtes_ido'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyujtes',
            name='celDatum',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fizetes',
            name='datum',
            field=models.DateField(default=datetime.date(2022, 6, 19)),
        ),
        migrations.AlterField(
            model_name='fizetes',
            name='ido',
            field=models.TimeField(default=datetime.time(10, 29, 0, 267027)),
        ),
        migrations.AlterField(
            model_name='gyujtes',
            name='datum',
            field=models.DateField(default=datetime.date(2022, 6, 19)),
        ),
        migrations.AlterField(
            model_name='gyujtes',
            name='ido',
            field=models.TimeField(default=datetime.time(10, 29, 0, 265455)),
        ),
    ]
