# Generated by Django 4.0.4 on 2022-06-19 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_gyujtes_celdatum_alter_fizetes_datum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fizetes',
            name='ido',
            field=models.TimeField(default=datetime.time(10, 31, 46, 489708)),
        ),
        migrations.AlterField(
            model_name='gyujtes',
            name='ido',
            field=models.TimeField(default=datetime.time(10, 31, 46, 488805)),
        ),
    ]
