# Generated by Django 4.0.4 on 2022-06-19 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_fizetes_ido_alter_gyujtes_ido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fizetes',
            name='ido',
            field=models.TimeField(default=datetime.time(10, 32, 6, 477813)),
        ),
        migrations.AlterField(
            model_name='gyujtes',
            name='ido',
            field=models.TimeField(default=datetime.time(10, 32, 6, 477088)),
        ),
    ]
