# Generated by Django 4.0.4 on 2022-06-24 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_felhasznalo_telefon_alter_fizetes_datum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fizetes',
            name='datum',
        ),
        migrations.RemoveField(
            model_name='fizetes',
            name='ido',
        ),
        migrations.RemoveField(
            model_name='gyujtes',
            name='datum',
        ),
        migrations.RemoveField(
            model_name='gyujtes',
            name='ido',
        ),
        migrations.AddField(
            model_name='fizetes',
            name='datumIdo_UTC',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 12, 14, 27, 207542, tzinfo=utc)),
        ),
    ]
