# Generated by Django 4.0.4 on 2022-06-24 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_fizetes_datum_remove_fizetes_ido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyujtes',
            name='datumIdo_UTC',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 12, 20, 44, 36252, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fizetes',
            name='datumIdo_UTC',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 12, 20, 44, 37211, tzinfo=utc)),
        ),
    ]
